### PR TITLE
Add support for dmaker.fan.p18

### PR DESCRIPTION
**Pull request by pooyashahidi**
Using FanP10's class for P18 similar to P11 and P15.
It fixes the issue #136

### CODE REVIEW

**Comment by syssi** [comment]
Are you aware of any missing or broken features of this devices?

**Comment by syssi** [comment]
Could you add some specs and model numbers to the README if possible?

**Comment by pooyashahidi** [comment]
> Are you aware of any missing or broken features of this devices?

I've tested the following features and they work:
- speed control (4 levels)
- raw speed control (0-100%)
- oscillation and angles
- timer
- child lock
- buzzer

the only things that do not work are:
- turning the indicator LED on and off
- the manual rotation

I opened an issue in python-miio for the rotation as I suspect that must also be a problem with P10 (possibly other models as well) both should expect uint8 for this service not "left" or "right". Unless I'm misunderstanding something here 😊

**Comment by pooyashahidi** [comment]
> Could you add some specs and model numbers to the README if possible?

I tried my best to provide accurate information from the [official site](https://www.mi.com/global/product/mi-smart-standing-fan-2/overview) following the only example that already had that information (p11).

**Comment by syssi** [comment]
Good job! Thanks for your support!

**Pull request merged**
