### PR TITLE
Add HACS compatibility

### LINKED ISSUE #48: HACS Integration
Hey!

Could you add this module to HACS repository?

Greetings

### PR DESCRIPTION
**Pull request by Ernst79**
Hi @syssi 

This PR adds HACS compatibility for your custom component. Also added the instructions in the readme.

Please note that after you merge this into the development branch, you should merge all your changes to the master branch. Apparently, HACS is using the master branch to download the files to home assistant. Right now, the default branch is development.

You also have to make a release afterwards to make it work in HACS.

Fixes #48, #49 and #37

### CODE REVIEW

**Comment by syssi** [comment]
Good job! Thanks a lot!

**Comment by syssi** [comment]
I've merge develop into master. Could you give it a try?

**Comment by Ernst79** [comment]
Yes, It works fine now in HACS. Thanks.

**Comment by Ernst79** [comment]
A next step could be to move your repository to here (https://github.com/custom-components), so it is included in HACS automatically, without people having to add your repository manually. You remain the owner of the new repository, so you have all the freedom to modify things like you have now. 

If you don’t have time, I can do it for you, just let me know. 

To open a repository, you (or I) have to ask ludeeus on discord to open a new folder.

**Comment by syssi** [comment]
I don't like the idea to move the repository to another GitHub account.

**Comment by Ernst79** [comment]
Ok, no problem. It works anyhow, just one step more to install. 

Thanks anyway for making this component.

**Comment by harrisony** [comment]
It can still be added as a default repository (without the repository being moved)

https://hacs.xyz/docs/publish/include

**Pull request merged**
